site_name: 'ğŸ›°ï¸ 01: Echoes Lost in Orbit'

nav:
  - Introduction: index.md
  - 'ğŸŸ¢ Beginner': beginner.md
  - 'ğŸŸ¡ Intermediate': intermediate.md
  - 'ğŸ”´ Expert': expert.md
  - 'Solutions':
      - 'ğŸŸ¢ Beginner': solutions/beginner.md
