apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: echo-server
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/steerpike/open-ecosystem-challenges.git
        revision: HEAD
        directories:
          - path: adventures/01-echoes-lost-in-orbit/intermediate/manifests/overlays/*
  template:
    metadata:
      name: echo-server-{{ path.basename}}
      labels:
        app.kubernetes.io/managed-by: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/steerpike/open-ecosystem-challenges.git
        targetRevision: HEAD
        path: adventures/01-echoes-lost-in-orbit/intermediate/manifests/overlays/{{ path.basename }}
      destination:
        server: https://kubernetes.default.svc
        namespace: echo-{{ path.basename }}
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true